# ---------- STAGE 1: deps ----------
FROM node:20-alpine AS deps
WORKDIR /app

COPY package*.json ./

# Desactivamos scripts como "prepare" (husky)
RUN npm ci --omit=dev --ignore-scripts


# ---------- STAGE 2: runner ----------
FROM node:20-alpine AS runner
WORKDIR /app

ENV NODE_ENV=production

COPY --from=deps /app/node_modules ./node_modules
COPY src ./src
COPY package*.json ./

EXPOSE 3000

CMD ["node", "src/server.js"]
